name: Laravel

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-tests:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    
    - name: Coping Env file
      run: cd /home && sudo cp .env /var/www/actions-runner/_work/Lexpal/Lexpal
    
